version: "3.8"

services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_ID=node1
      - IS_LEADER=true
      - PEERS=node2:50052,node3:50053
      - PORT=50051
    ports:
      - "50051:50051"

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_ID=node2
      - IS_LEADER=false
      - PEERS=node1:50051
      - PORT=50052
    ports:
      - "50052:50052"

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_ID=node3
      - IS_LEADER=false
      - PEERS=node1:50051
      - PORT=50053
    ports:
      - "50053:50053"
